spring.datasource.generate-unique-name=false
spring.datasource.url=${PLUGPASS_DATABASE_URL:jdbc:h2:file:/data/plugpass}
spring.datasource.username=${PLUGPASS_DATABASE_USERNAME:plugpass}
spring.datasource.password=${PLUGPASS_DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.h2.console.enabled=false
management.server.port=${MANAGEMENT_SERVER_PORT:8081}
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=never
