import { afterEach, describe, expect, it, vi } from 'vitest'
import { effectScope } from 'vue'
import { useCurrentLocation } from './useCurrentLocation'

afterEach(() => { vi.useRealTimers() })
function position(latitude = 37.5, longitude = 127): GeolocationPosition {
  return { coords: { latitude, longitude, accuracy: 1, altitude: null, altitudeAccuracy: null, heading: null, speed: null, toJSON: () => ({}) }, timestamp: 0, toJSON: () => ({}) }
}

describe('명시적인 현재 위치 요청', () => {
  it('생성만으로 권한을 요청하지 않는다', () => {
    const getCurrentPosition = vi.fn<Geolocation['getCurrentPosition']>()
    vi.stubGlobal('navigator', { geolocation: { getCurrentPosition } })
    const location = useCurrentLocation()
    expect(location.status.value).toBe('idle')
    expect(getCurrentPosition).not.toHaveBeenCalled()
  })
  it('클릭 요청 중 상태와 성공 좌표를 제공한다', async () => {
    const getCurrentPosition = vi.fn<Geolocation['getCurrentPosition']>()
    vi.stubGlobal('navigator', { geolocation: { getCurrentPosition } })
    const location = useCurrentLocation()
    const request = location.requestLocation()
    expect(location.status.value).toBe('loading')
    expect(getCurrentPosition.mock.calls[0]?.[2]).toMatchObject({ timeout: 10000, maximumAge: 0 })
    getCurrentPosition.mock.calls[0]?.[0](position())
    await expect(request).resolves.toEqual({ latitude: 37.5, longitude: 127 })
    expect(location.coordinates.value).toEqual({ latitude: 37.5, longitude: 127 })
    expect(location.status.value).toBe('success')
    expect(location.error.value).toBeNull()
  })
  it.each([[1, '위치 권한이 거부되었습니다'], [2, '현재 위치를 확인할 수 없습니다'], [3, '10초 안에 위치를 확인하지 못했습니다']])('위치 오류 %s를 안내하고 좌표를 남기지 않는다', async (code, message) => {
    const getCurrentPosition = vi.fn<Geolocation['getCurrentPosition']>()
    vi.stubGlobal('navigator', { geolocation: { getCurrentPosition } })
    const location = useCurrentLocation()
    const request = location.requestLocation()
    getCurrentPosition.mock.calls[0]?.[1]?.({ code, message: 'browser error', PERMISSION_DENIED: 1, POSITION_UNAVAILABLE: 2, TIMEOUT: 3 })
    await expect(request).resolves.toBeNull()
    expect(location.status.value).toBe('error')
    expect(location.error.value).toContain(message)
    expect(location.coordinates.value).toBeNull()
  })
  it('브라우저 callback이 없어도 정확히 10초에 종료하고 늦은 성공을 무시한다', async () => {
    vi.useFakeTimers()
    const getCurrentPosition = vi.fn<Geolocation['getCurrentPosition']>()
    vi.stubGlobal('navigator', { geolocation: { getCurrentPosition } })
    const location = useCurrentLocation()
    const request = location.requestLocation()
    await vi.advanceTimersByTimeAsync(9999)
    expect(location.status.value).toBe('loading')
    await vi.advanceTimersByTimeAsync(1)
    await expect(request).resolves.toBeNull()
    getCurrentPosition.mock.calls[0]?.[0](position())
    expect(location.status.value).toBe('error')
    expect(location.error.value).toContain('10초')
    expect(location.coordinates.value).toBeNull()
  })
  it('취소 후 늦은 위치가 예시 위치 선택을 덮지 않는다', async () => {
    const getCurrentPosition = vi.fn<Geolocation['getCurrentPosition']>()
    vi.stubGlobal('navigator', { geolocation: { getCurrentPosition } })
    const location = useCurrentLocation()
    const request = location.requestLocation()
    location.cancel()
    getCurrentPosition.mock.calls[0]?.[0](position(38, 128))
    await expect(request).resolves.toBeNull()
    expect(location.status.value).toBe('idle')
    expect(location.coordinates.value).toBeNull()
  })
  it('새 요청을 시작하면 이전 callback은 최신 요청에 영향을 주지 않는다', async () => {
    const getCurrentPosition = vi.fn<Geolocation['getCurrentPosition']>()
    vi.stubGlobal('navigator', { geolocation: { getCurrentPosition } })
    const location = useCurrentLocation()
    const first = location.requestLocation()
    const second = location.requestLocation()
    getCurrentPosition.mock.calls[1]?.[0](position(38, 128))
    getCurrentPosition.mock.calls[0]?.[1]?.({ code: 1, message: 'late', PERMISSION_DENIED: 1, POSITION_UNAVAILABLE: 2, TIMEOUT: 3 })
    await expect(first).resolves.toBeNull()
    await expect(second).resolves.toEqual({ latitude: 38, longitude: 128 })
    expect(location.status.value).toBe('success')
    expect(location.error.value).toBeNull()
  })
  it('화면 scope가 끝나면 대기 요청과 타이머를 정리한다', async () => {
    vi.useFakeTimers()
    const getCurrentPosition = vi.fn<Geolocation['getCurrentPosition']>()
    vi.stubGlobal('navigator', { geolocation: { getCurrentPosition } })
    const scope = effectScope()
    const location = scope.run(() => useCurrentLocation())
    const request = location?.requestLocation()
    scope.stop()
    getCurrentPosition.mock.calls[0]?.[0](position())
    await expect(request).resolves.toBeNull()
    expect(location?.coordinates.value).toBeNull()
    expect(vi.getTimerCount()).toBe(0)
  })
  it('지원하지 않는 브라우저에서는 대안 안내를 제공한다', async () => {
    vi.stubGlobal('navigator', {})
    const location = useCurrentLocation()
    await expect(location.requestLocation()).resolves.toBeNull()
    expect(location.status.value).toBe('error')
    expect(location.error.value).toContain('검증용 예시 위치')
  })
  it.each([[NaN, 127], [91, 127], [37.5, Infinity], [37.5, -181]])('잘못된 위치 좌표 %s/%s를 검색 입력으로 넘기지 않는다', async (latitude, longitude) => {
    const getCurrentPosition = vi.fn<Geolocation['getCurrentPosition']>()
    vi.stubGlobal('navigator', { geolocation: { getCurrentPosition } })
    const location = useCurrentLocation()
    const request = location.requestLocation()
    getCurrentPosition.mock.calls[0]?.[0](position(latitude, longitude))
    await expect(request).resolves.toBeNull()
    expect(location.status.value).toBe('error')
    expect(location.coordinates.value).toBeNull()
  })
})
